# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: DotNetCoreCLI@2
  displayName: Build FileJoiner
  inputs:
    command: 'build'
    projects: '**/FileJoiner.csproj'

- task: DotNetCoreCLI@2
  displayName: Publish FileJoiner
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/FileJoiner.csproj'
    arguments: '/p:PublishProfile=$(System.DefaultWorkingDirectory)/FileJoinerNet/FileJoiner/FileJoiner/Properties/PublishProfiles/FolderProfile.pubxml  --configuration Release --output  $(Build.ArtifactStagingDirectory)/FileJoinerNet/FileJoiner/FileJoiner/Publish/Publish.zip'
    modifyOutputPath: false