# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: DotNetCoreCLI@2
  displayName: Build FileJoiner
  inputs:
    command: 'build'
    projects: '**/FileJoiner.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/FileJoiner.csproj'
    arguments: '/p:PublishProfile=$(System.DefaultWorkingDirectory)/FileJoinerNet/FileJoiner/FileJoiner/Properties/PublishProfiles/FolderProfile.pubxml'
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/bin/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

# - task: DownloadBuildArtifacts@0
#   inputs:
#     buildType: 'current'
#     downloadType: 'single'
#     artifactName: 'buildArtifact'
#     downloadPath: '$(System.ArtifactsDirectory)'



# - task: DotNetCoreCLI@2
#   displayName: Publish FileJoiner
#   inputs:
#     command: 'publish'
#     publishWebProjects: false
#     projects: '**/FileJoiner.csproj'
#     arguments: '
#     modifyOutputPath: false


